export const ROUTES = {
  home: '/',
  designSystem: '/design-system',
  dashboardFoundation: '/design-system/dashboard-foundation',
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  superAdmin: {
    dashboard: '/super-admin/dashboard',
    schools: '/super-admin/schools',
    newSchool: '/super-admin/schools/new',
    subscriptions: '/super-admin/subscriptions',
    subscriptionUsage: '/super-admin/subscriptions/usage',
    billing: '/super-admin/billing',
    users: '/super-admin/users',
  },
  schoolAdmin: {
    dashboard: '/school-admin/dashboard',
    students: '/school-admin/students',
    newStudent: '/school-admin/students/new',
    teachers: '/school-admin/teachers',
    newTeacher: '/school-admin/teachers/new',
    classes: '/school-admin/classes',
    attendance: '/school-admin/attendance',
    attendanceReports: '/school-admin/attendance/reports',
    fees: '/school-admin/fees',
    feeStructures: '/school-admin/fees/structures',
    feeInvoices: '/school-admin/fees/invoices',
    feePayments: '/school-admin/fees/payments',
    feeDefaulters: '/school-admin/fees/defaulters',
  },
} as const;
